# Generated by Django 4.2.3 on 2023-07-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=120)),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
