# Generated by Django 4.2.3 on 2023-07-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_produtos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to='imagem'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(max_length=120, null=''),
        ),
    ]
